# Project configuration for Clippy Rust code linter.
# See full lints list at:
# https://rust-lang.github.io/rust-clippy/master/index.html

msrv = "1.65.0"
standard-macro-braces = [
    { name = "assert", brace = "(" },
    { name = "assert_eq", brace = "(" },
    { name = "assert_ne", brace = "(" },
    { name = "format", brace = "(" },
    { name = "format_ident", brace = "(" },
    { name = "matches", brace = "(" },
    { name = "panic", brace = "(" },
    { name = "parse_quote", brace = "{" },
    { name = "quote", brace = "{" },
    { name = "quote_spanned", brace = "{" },
    { name = "todo", brace = "(" },
    { name = "unimplemented", brace = "(" },
    { name = "unreachable", brace = "(" },
    { name = "vec", brace = "[" },
]
