(function() {var implementors = {};
implementors["syn"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.AttrStyle.html' title='enum syn::AttrStyle'>AttrStyle</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.TraitBoundModifier.html' title='enum syn::TraitBoundModifier'>TraitBoundModifier</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.StrStyle.html' title='enum syn::StrStyle'>StrStyle</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.IntTy.html' title='enum syn::IntTy'>IntTy</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.FloatTy.html' title='enum syn::FloatTy'>FloatTy</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.BinOpToken.html' title='enum syn::BinOpToken'>BinOpToken</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.DelimToken.html' title='enum syn::DelimToken'>DelimToken</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.BinOp.html' title='enum syn::BinOp'>BinOp</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.UnOp.html' title='enum syn::UnOp'>UnOp</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.Mutability.html' title='enum syn::Mutability'>Mutability</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='trait core::marker::Copy'>Copy</a> for <a class='enum' href='syn/enum.Unsafety.html' title='enum syn::Unsafety'>Unsafety</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
